services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - PGURL=postgres://postgres:postgres@db:5432/professores
      - INIT_SQL=db/init.sql
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: professores

  frontend:
      build: ./frontend
      restart: always
      ports:
      - "3000:3000"
      depends_on:
      - backend